# SITE CONFIGURATION
baseurl: ""
url: "http://blog.emcauliffe.ca"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Ethan McAuliffe's Blog
  avatar: #assets/img/avatar.png
  favicon: "https://emcauliffe.ca/Images/favicon.png"
  gravatar: # Email MD5 hash
  description: "An assortment of projects I've completed or am working on." # used by search engines

  # Header and footer text
  #header_text: >
     #<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

    # <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image:
  footer_text:    â€

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: emcauliffe
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/ethan-mcauliffe/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-113342409-1"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
